name: saferm-test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  saferm-test:
    name: saferm-test
    runs-on: ubuntu-latest
    steps:
      - name: go-env
        uses: actions/setup-go@v1
        with:
          go-version: "1.15"
      - name: Checkout
        uses: actions/checkout@v2
      - run: go test ./...